-- Fix SYS_LOGININFOR table schema to support longer browser strings
-- This resolves the "Value too long for column BROWSER VARCHAR(50)" error

-- Increase column sizes for browser, OS, and other fields that may have user agent data
ALTER TABLE SYS_LOGININFOR ALTER COLUMN browser VARCHAR(500);
ALTER TABLE SYS_LOGININFOR ALTER COLUMN os VARCHAR(255);
ALTER TABLE SYS_LOGININFOR ALTER COLUMN ipaddr VARCHAR(255);
ALTER TABLE SYS_LOGININFOR ALTER COLUMN login_location VARCHAR(500);
ALTER TABLE SYS_LOGININFOR ALTER COLUMN msg VARCHAR(1000);

-- Also fix SYS_OPER_LOG if it has similar issues
ALTER TABLE SYS_OPER_LOG ALTER COLUMN method VARCHAR(1000);
ALTER TABLE SYS_OPER_LOG ALTER COLUMN oper_url VARCHAR(1000);
ALTER TABLE SYS_OPER_LOG ALTER COLUMN oper_location VARCHAR(1000);
ALTER TABLE SYS_OPER_LOG ALTER COLUMN oper_param CLOB;
ALTER TABLE SYS_OPER_LOG ALTER COLUMN json_result CLOB;
ALTER TABLE SYS_OPER_LOG ALTER COLUMN error_msg CLOB;
