server:
  port: 8081

spring:
  application:
    name: bms
  datasource:
    url: jdbc:h2:file:./data/bms;MODE=Oracle;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bms: DEBUG
