-- 1. User Table
drop table if exists sys_user;
drop sequence if exists sys_user_seq;
create sequence sys_user_seq start with 100 increment by 1;
create table sys_user (
  user_id           bigint          not null,
  login_name        varchar(30)     not null,
  user_name         varchar(30)     default '',
  user_type         varchar(2)      default '00',
  email             varchar(50)     default '',
  phonenumber       varchar(11)     default '',
  sex               varchar(1)         default '0',
  avatar            varchar(100)    default '',
  password          varchar(100)    default '',
  salt              varchar(20)     default '',
  status            varchar(1)         default '0',
  del_flag          varchar(1)         default '0',
  login_ip          varchar(128)    default '',
  login_date        timestamp       null,
  pwd_update_date   timestamp       null,
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default null,
  primary key (user_id)
);
-- 3. Role Table
drop table if exists sys_role;
create table sys_role (
  role_id           bigint          generated by default as identity,
  role_name         varchar(30)     not null,
  role_key          varchar(100)    not null,
  role_sort         int             not null,
  data_scope        varchar(1)         default '1',
  status            varchar(1)         not null,
  del_flag          varchar(1)         default '0',
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default null,
  primary key (role_id)
);
-- 4. Menu Table
drop table if exists sys_menu;
create table sys_menu (
  menu_id           bigint          generated by default as identity,
  menu_name         varchar(50)     not null,
  parent_id         bigint          default 0,
  order_num         int             default 0,
  url               varchar(200)    default '#',
  target            varchar(20)     default '',
  menu_type         varchar(1)         default '',
  visible           varchar(1)         default '0',
  is_refresh        varchar(1)      default '1',
  perms             varchar(100)    default null,
  icon              varchar(100)    default '#',
  status            varchar(1)         default '0',
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default '',
  primary key (menu_id)
);
-- 5. User-Role Table
drop table if exists sys_user_role;
create table sys_user_role (
  user_id   bigint not null,
  role_id   bigint not null,
  primary key(user_id, role_id)
);
-- 6. Role-Menu Table
drop table if exists sys_role_menu;
create table sys_role_menu (
  role_id   bigint not null,
  menu_id   bigint not null,
  primary key(role_id, menu_id)
);
-- 7. Dict Type Table
drop table if exists sys_dict_type;
create table sys_dict_type (
  dict_id         bigint          generated by default as identity,
  dict_name       varchar(100)    default '',
  dict_type       varchar(100)    default '',
  status          varchar(1)      default '0',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (dict_id)
);
create unique index sys_dict_type_index on sys_dict_type (dict_type);
-- 8. Dict Data Table
drop table if exists sys_dict_data;
create table sys_dict_data (
  dict_code       bigint          generated by default as identity,
  dict_sort       int             default 0,
  dict_label      varchar(100)    default '',
  dict_value      varchar(100)    default '',
  dict_type       varchar(100)    default '',
  css_class       varchar(100)    default null,
  list_class      varchar(100)    default null,
  is_default      varchar(1)         default 'N',
  status          varchar(1)         default '0',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (dict_code)
);
-- 9. Config Table
drop table if exists sys_config;
create table sys_config (
  config_id       bigint          generated by default as identity,
  config_name     varchar(100)    default '',
  config_key      varchar(100)    default '',
  config_value    varchar(500)    default '',
  config_type     varchar(1)      default 'N',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (config_id)
);
-- 10. Post Table
drop table if exists sys_post;
create table sys_post (
  post_id         bigint          generated by default as identity,
  post_code       varchar(64)     not null,
  post_name       varchar(50)     not null,
  post_sort       int             not null,
  status          varchar(1)         not null,
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (post_id)
);
-- 11. User-Post Table
drop table if exists sys_user_post;
create table sys_user_post (
  user_id   bigint not null,
  post_id   bigint not null,
  primary key(user_id, post_id)
);
-- 12. Login Info Table
drop table if exists sys_logininfor;
drop sequence if exists sys_logininfor_seq;
create sequence sys_logininfor_seq start with 100 increment by 1;
create table sys_logininfor (
  info_id         bigint          not null,
  login_name      varchar(50)     default '',
  status          varchar(1)         default '0',
  ipaddr          varchar(128)    default '',
  login_location  varchar(255)    default '',
  browser         varchar(50)     default '',
  os              varchar(50)     default '',
  msg             varchar(255)    default '',
  login_time      timestamp       default current_timestamp,
  primary key (info_id)
);
-- 13. Operation Log Table
drop table if exists sys_oper_log;
drop sequence if exists sys_oper_log_seq;
create sequence sys_oper_log_seq start with 100 increment by 1;
create table sys_oper_log (
  oper_id         bigint          not null,
  title           varchar(50)     default '',
  business_type   int             default 0,
  method          varchar(500)    default '',
  request_method  varchar(20)     default '',
  operator_type   int             default 0,
  oper_name       varchar(50)     default '',
  dept_name       varchar(50)     default '',
  oper_url        varchar(500)    default '',
  oper_ip         varchar(128)    default '',
  oper_location   varchar(500)    default '',
  oper_param      varchar(8000)   default '',
  json_result     varchar(16000)  default '',
  status          int             default 0,
  error_msg       varchar(8000)   default '',
  oper_time       timestamp       default current_timestamp,
  cost_time       bigint          default 0,
  primary key (oper_id)
);
create index sys_oper_log_idx on sys_oper_log (oper_time);
-- 14. Job Table (Quartz)
drop table if exists sys_job;
create table sys_job (
  job_id          bigint          generated by default as identity,
  job_name        varchar(64)     not null,
  job_group       varchar(64)     default 'DEFAULT',
  invoke_target   varchar(500)    not null,
  cron_expression varchar(255)    default '',
  misfire_policy  varchar(20)     default '3',
  concurrent      varchar(1)      default '1',
  status          varchar(1)      default '0',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default '',
  primary key (job_id)
);
-- 15. Job Log Table
drop table if exists sys_job_log;
create table sys_job_log (
  job_log_id      bigint          generated by default as identity,
  job_name        varchar(64)     not null,
  job_group       varchar(64)     not null,
  invoke_target   varchar(500)    not null,
  job_message     varchar(500)    default '',
  status          varchar(1)         default '0',
  exception_info  varchar(2000)   default '',
  start_time      timestamp       default current_timestamp,
  end_time        timestamp       null,
  primary key (job_log_id)
);
-- 16. Gen Table (Code Generator)
drop table if exists gen_table;
create table gen_table (
  table_id          bigint          generated by default as identity,
  table_name        varchar(200)    default '',
  table_comment     varchar(500)    default '',
  sub_table_name    varchar(64)     default null,
  sub_table_fk_name varchar(64)     default null,
  class_name        varchar(100)    default '',
  tpl_category      varchar(200)    default 'crud',
  package_name      varchar(100)    default '',
  module_name       varchar(30)     default '',
  business_name     varchar(30)     default '',
  function_name     varchar(50)     default '',
  function_author   varchar(50)     default '',
  form_col_num      int             default 1,
  gen_type          varchar(1)         default '0',
  gen_path          varchar(200)    default '/',
  options           varchar(1000)   default null,
  tree_code         varchar(200)    default null,
  tree_parent_code  varchar(200)    default null,
  tree_name         varchar(200)    default null,
  parent_menu_id    varchar(64)     default null,
  parent_menu_name  varchar(64)     default null,
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default null,
  primary key (table_id)
);
-- 17. Gen Table Column
drop table if exists gen_table_column;
create table gen_table_column (
  column_id       bigint          generated by default as identity,
  table_id        bigint          default null,
  column_name     varchar(200)    default '',
  column_comment  varchar(500)    default '',
  column_type     varchar(100)    default '',
  java_type       varchar(500)    default '',
  java_field      varchar(200)    default '',
  is_pk           varchar(1)         default null,
  is_increment    varchar(1)         default null,
  is_required     varchar(1)         default null,
  is_insert       varchar(1)         default null,
  is_edit         varchar(1)         default null,
  is_list         varchar(1)         default null,
  is_query        varchar(1)         default null,
  query_type      varchar(200)    default 'EQ',
  html_type       varchar(200)    default '',
  dict_type       varchar(200)    default '',
  sort            int             default 0,
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  primary key (column_id)
);
-- Quartz Tables (H2 compatible)
drop table if exists QRTZ_FIRED_TRIGGERS;
drop table if exists QRTZ_PAUSED_TRIGGER_GRPS;
drop table if exists QRTZ_SCHEDULER_STATE;
drop table if exists QRTZ_LOCKS;
drop table if exists QRTZ_SIMPLE_TRIGGERS;
drop table if exists QRTZ_SIMPROP_TRIGGERS;
drop table if exists QRTZ_CRON_TRIGGERS;
drop table if exists QRTZ_BLOB_TRIGGERS;
drop table if exists QRTZ_TRIGGERS;
drop table if exists QRTZ_JOB_DETAILS;
drop table if exists QRTZ_CALENDARS;
create table QRTZ_JOB_DETAILS (
  sched_name        varchar(120)    not null,
  job_name          varchar(200)    not null,
  job_group         varchar(200)    not null,
  description       varchar(250)    null,
  job_class_name    varchar(250)    not null,
  is_durable        varchar(1)      not null,
  is_nonconcurrent  varchar(1)      not null,
  is_update_data    varchar(1)      not null,
  requests_recovery varchar(1)      not null,
  job_data          blob            null,
  primary key (sched_name, job_name, job_group)
);
create table QRTZ_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  job_name       varchar(200)    not null,
  job_group      varchar(200)    not null,
  description    varchar(250)    null,
  next_fire_time bigint          null,
  prev_fire_time bigint          null,
  priority       integer         null,
  trigger_state  varchar(16)     not null,
  trigger_type   varchar(8)      not null,
  start_time     bigint          not null,
  end_time       bigint          null,
  calendar_name  varchar(200)    null,
  misfire_instr  smallint        null,
  job_data       blob            null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, job_name, job_group) references QRTZ_JOB_DETAILS(sched_name, job_name, job_group)
);
create table QRTZ_SIMPLE_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  repeat_count   bigint          not null,
  repeat_interval bigint         not null,
  times_triggered bigint         not null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
create table QRTZ_CRON_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  cron_expression varchar(200)   not null,
  time_zone_id   varchar(80)     null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
create table QRTZ_BLOB_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  blob_data      blob            null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);
create table QRTZ_CALENDARS (
  sched_name     varchar(120)    not null,
  calendar_name  varchar(200)    not null,
  calendar       blob            not null,
  primary key (sched_name, calendar_name)
);
create table QRTZ_PAUSED_TRIGGER_GRPS (
  sched_name     varchar(120)    not null,
  trigger_group  varchar(200)    not null,
  primary key (sched_name, trigger_group)
);
create table QRTZ_FIRED_TRIGGERS (
  sched_name      varchar(120)    not null,
  entry_id        varchar(95)     not null,
  trigger_name    varchar(200)    not null,
  trigger_group   varchar(200)    not null,
  instance_name   varchar(200)    not null,
  fired_time      bigint          not null,
  sched_time      bigint          not null,
  priority        integer         not null,
  state           varchar(16)     not null,
  job_name        varchar(200)    null,
  job_group       varchar(200)    null,
  is_nonconcurrent varchar(1)     null,
  requests_recovery varchar(1)    null,
  primary key (sched_name, entry_id)
);
create table QRTZ_SCHEDULER_STATE (
  sched_name      varchar(120)    not null,
  instance_name   varchar(200)    not null,
  last_checkin_time bigint        not null,
  checkin_interval bigint         not null,
  primary key (sched_name, instance_name)
);
create table QRTZ_LOCKS (
  sched_name      varchar(120)    not null,
  lock_name       varchar(40)     not null,
  primary key (sched_name, lock_name)
);
create table QRTZ_SIMPROP_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  str_prop_1     varchar(512)    null,
  str_prop_2     varchar(512)    null,
  str_prop_3     varchar(512)    null,
  int_prop_1     integer         null,
  int_prop_2     integer         null,
  long_prop_1    bigint          null,
  long_prop_2    bigint          null,
  dec_prop_1     numeric(13,4)   null,
  dec_prop_2     numeric(13,4)   null,
  bool_prop_1    varchar(1)      null,
  bool_prop_2    varchar(1)      null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

-- AI Knowledge Base Table
drop sequence if exists ai_knowledge_seq;
create sequence ai_knowledge_seq start with 100 increment by 1;
create table ai_knowledge (
  knowledge_id    bigint          not null,
  title           varchar(200)    not null,
  content         clob            not null,
  category        varchar(50)     default '',
  keywords        varchar(500)    default '',
  status          varchar(1)      default '1',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (knowledge_id)
);
create index ai_knowledge_category_idx on ai_knowledge (category);
create index ai_knowledge_status_idx on ai_knowledge (status);
