-- =====================================================
-- VANTAGE ADMIN - Master Database Schema
-- Standardized for H2 (Oracle Mode)
-- =====================================================

-- 1. User Table
drop table if exists sys_user;
drop sequence if exists sys_user_seq;
create sequence sys_user_seq start with 100 increment by 1;
create table sys_user (
  user_id           bigint          not null,
  login_name        varchar(30)     not null,
  user_name         varchar(30)     default '',
  user_type         varchar(2)      default '00',
  email             varchar(50)     default '',
  phonenumber       varchar(11)     default '',
  sex               varchar(1)         default '0',
  avatar            varchar(100)    default '',
  password          varchar(100)    default '',
  salt              varchar(20)     default '',
  status            varchar(1)         default '0',
  del_flag          varchar(1)         default '0',
  login_ip          varchar(128)    default '',
  login_date        timestamp       null,
  pwd_update_date   timestamp       null,
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default null,
  primary key (user_id)
);

-- 3. Role Table
drop table if exists sys_role;
create table sys_role (
  role_id           bigint          generated by default as identity,
  role_name         varchar(30)     not null,
  role_key          varchar(100)    not null,
  role_sort         int             not null,
  data_scope        varchar(1)         default '1',
  status            varchar(1)         not null,
  del_flag          varchar(1)         default '0',
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default null,
  primary key (role_id)
);

-- 4. Menu Table
drop table if exists sys_menu;
create table sys_menu (
  menu_id           bigint          generated by default as identity,
  menu_name         varchar(50)     not null,
  parent_id         bigint          default 0,
  order_num         int             default 0,
  url               varchar(200)    default '#',
  target            varchar(20)     default '',
  menu_type         varchar(1)         default '',
  visible           varchar(1)         default '0',
  is_refresh        varchar(1)      default '1',
  perms             varchar(100)    default null,
  icon              varchar(100)    default '#',
  status            varchar(1)         default '0',
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default '',
  primary key (menu_id)
);

-- 5. User-Role Table
drop table if exists sys_user_role;
create table sys_user_role (
  user_id   bigint not null,
  role_id   bigint not null,
  primary key(user_id, role_id)
);

-- 6. Role-Menu Table
drop table if exists sys_role_menu;
create table sys_role_menu (
  role_id   bigint not null,
  menu_id   bigint not null,
  primary key(role_id, menu_id)
);

-- 7. Dict Type Table
drop table if exists sys_dict_type;
create table sys_dict_type (
  dict_id         bigint          generated by default as identity,
  dict_name       varchar(100)    default '',
  dict_type       varchar(100)    default '',
  status          varchar(1)      default '0',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (dict_id)
);
create unique index sys_dict_type_index on sys_dict_type (dict_type);

-- 8. Dict Data Table
drop table if exists sys_dict_data;
create table sys_dict_data (
  dict_code       bigint          generated by default as identity,
  dict_sort       int             default 0,
  dict_label      varchar(100)    default '',
  dict_value      varchar(100)    default '',
  dict_type       varchar(100)    default '',
  css_class       varchar(100)    default null,
  list_class      varchar(100)    default null,
  is_default      varchar(1)         default 'N',
  status          varchar(1)         default '0',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (dict_code)
);

-- 9. Config Table
drop table if exists sys_config;
create table sys_config (
  config_id       bigint          generated by default as identity,
  config_name     varchar(100)    default '',
  config_key      varchar(100)    default '',
  config_value    varchar(500)    default '',
  config_type     varchar(1)      default 'N',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (config_id)
);

-- 10. Post Table
drop table if exists sys_post;
create table sys_post (
  post_id         bigint          generated by default as identity,
  post_code       varchar(64)     not null,
  post_name       varchar(50)     not null,
  post_sort       int             not null,
  status          varchar(1)         not null,
  create_by       varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark            varchar(500)    default null,
  primary key (post_id)
);

-- 11. User-Post Table
drop table if exists sys_user_post;
create table sys_user_post (
  user_id   bigint not null,
  post_id   bigint not null,
  primary key(user_id, post_id)
);

-- 12. Login Info Table (Monitor) - Standardized column sizes
drop table if exists sys_logininfor;
drop sequence if exists sys_logininfor_seq;
create sequence sys_logininfor_seq start with 100 increment by 1;
create table sys_logininfor (
  info_id         bigint          not null,
  login_name      varchar(50)     default '',
  status          varchar(1)         default '0',
  ipaddr          varchar(255)    default '',
  login_location  varchar(500)    default '',
  browser         varchar(500)    default '',
  os              varchar(255)    default '',
  msg             varchar(1000)    default '',
  login_time      timestamp       default current_timestamp,
  primary key (info_id)
);

-- 13. Operation Log Table (Monitor) - Standardized column sizes
drop table if exists sys_oper_log;
drop sequence if exists sys_oper_log_seq;
create sequence sys_oper_log_seq start with 100 increment by 1;
create table sys_oper_log (
  oper_id         bigint          not null,
  title           varchar(50)     default '',
  business_type   int             default 0,
  method          varchar(1000)    default '',
  request_method  varchar(20)     default '',
  operator_type   int             default 0,
  oper_name       varchar(50)     default '',
  dept_name       varchar(50)     default '',
  oper_url        varchar(1000)    default '',
  oper_ip         varchar(255)    default '',
  oper_location   varchar(1000)    default '',
  oper_param      clob,
  json_result     clob,
  status          int             default 0,
  error_msg       clob,
  oper_time       timestamp       default current_timestamp,
  cost_time       bigint          default 0,
  old_values      clob,
  new_values      clob,
  changed_fields  varchar(2000),
  primary key (oper_id)
);
create index sys_oper_log_idx on sys_oper_log (oper_time);

-- 14. Job Table (Quartz)
drop table if exists sys_job;
create table sys_job (
  job_id              bigint          generated by default as identity,
  job_name            varchar(64)     not null,
  job_group           varchar(64)     default 'DEFAULT',
  invoke_target       varchar(500),
  cron_expression     varchar(255)    default '',
  misfire_policy      varchar(20)     default '3',
  concurrent          varchar(1)      default '1',
  status              varchar(1)      default '0',
  create_by           varchar(64)     default '',
  create_time         timestamp       default current_timestamp,
  update_by           varchar(64)     default '',
  update_time         timestamp       null,
  remark              varchar(500)    default '',
  max_retry_count     integer         default 0,
  retry_interval      integer         default 60,
  timeout_seconds     integer         default 3600,
  notify_on_failure   boolean         default false,
  notification_emails varchar(500)    default '',
  email_template_id   bigint          default null,
  webhook_url         varchar(500)    default '',
  dependent_job_ids   varchar(500)    default '',
  time_zone           varchar(50)     default 'UTC',
  allow_holiday       boolean         default true,
  template_name       varchar(64)     default '',
  job_type            varchar(20)     default 'BEAN',
  report_id           bigint          default null,
  report_email_group  varchar(500),
  webhook_token       varchar(64)     default '',
  primary key (job_id)
);

-- 15. Job Log Table
drop table if exists sys_job_log;
create table sys_job_log (
  job_log_id          bigint          generated by default as identity,
  job_id              bigint          default null,
  job_name            varchar(64)     not null,
  job_group           varchar(64)     not null,
  invoke_target       varchar(500),
  job_message         varchar(2000)   default '',
  status              varchar(1)      default '0',
  exception_info      varchar(4000)   default '',
  execution_duration  bigint          default 0,
  retry_count         integer         default 0,
  start_time          timestamp       default current_timestamp,
  end_time            timestamp       null,
  create_time         timestamp       default current_timestamp,
  primary key (job_log_id)
);

-- 16. Gen Table (Code Generator)
drop table if exists gen_table;
create table gen_table (
  table_id          bigint          generated by default as identity,
  table_name        varchar(200)    default '',
  table_comment     varchar(500)    default '',
  sub_table_name    varchar(64)     default null,
  sub_table_fk_name varchar(64)     default null,
  class_name        varchar(100)    default '',
  tpl_category      varchar(200)    default 'crud',
  package_name      varchar(100)    default '',
  module_name       varchar(30)     default '',
  business_name     varchar(30)     default '',
  function_name     varchar(50)     default '',
  function_author   varchar(50)     default '',
  form_col_num      int             default 1,
  gen_type          varchar(1)         default '0',
  gen_path          varchar(200)    default '/',
  options           varchar(1000)   default null,
  tree_code         varchar(200)    default null,
  tree_parent_code  varchar(200)    default null,
  tree_name         varchar(200)    default null,
  parent_menu_id    varchar(64)     default null,
  parent_menu_name  varchar(64)     default null,
  create_by         varchar(64)     default '',
  create_time       timestamp       default current_timestamp,
  update_by         varchar(64)     default '',
  update_time       timestamp       null,
  remark            varchar(500)    default null,
  primary key (table_id)
);

-- 17. Gen Table Column
drop table if exists gen_table_column;
create table gen_table_column (
  column_id       bigint          generated by default as identity,
  table_id        bigint          default null,
  column_name     varchar(200)    default '',
  column_comment  varchar(500)    default '',
  column_type     varchar(100)    default '',
  java_type       varchar(500)    default '',
  java_field      varchar(200)    default '',
  is_pk           varchar(1)         default null,
  is_increment    varchar(1)         default null,
  is_required     varchar(1)         default null,
  is_insert       varchar(1)         default null,
  is_edit         varchar(1)         default null,
  is_list         varchar(1)         default null,
  is_query        varchar(1)         default null,
  query_type      varchar(200)    default 'EQ',
  html_type       varchar(200)    default '',
  dict_type       varchar(200)    default '',
  sort            int             default 0,
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  primary key (column_id)
);

-- 18. Multi-Datasource Tables
drop table if exists sys_datasource;
create sequence sys_datasource_seq start with 100 increment by 1;
create table sys_datasource (
    datasource_id   bigint          not null,
    datasource_name varchar(100)    not null,
    datasource_key  varchar(50)     not null unique,
    db_type         varchar(20)     not null,
    url             varchar(500)    not null,
    username        varchar(100)    not null,
    password        varchar(500)    not null,
    driver_class    varchar(200)    not null,
    status          varchar(1)      default '0',
    create_by       varchar(64)     default '',
    create_time     timestamp       default current_timestamp,
    update_by       varchar(64)     default '',
    update_time     timestamp       null,
    remark          varchar(500)    default '',
    last_test_time  timestamp       null,
    last_test_status varchar(1)     default '0',
    primary key (datasource_id)
);

drop table if exists sys_datasource_meta;
create sequence sys_datasource_meta_seq start with 100 increment by 1;
create table sys_datasource_meta (
    meta_id             bigint          not null,
    datasource_id       bigint          not null,
    table_name          varchar(200)    not null,
    table_comment       varchar(500),
    columns_meta        clob,
    last_sync_time      timestamp       default current_timestamp,
    primary key (meta_id),
    foreign key (datasource_id) references sys_datasource(datasource_id) on delete cascade
);

-- 19. Report Module Tables
drop table if exists sys_report;
create sequence sys_report_seq start with 100 increment by 1;
create table sys_report (
    report_id         bigint          not null,
    report_name       varchar(100)    not null,
    report_key        varchar(50)     not null unique,
    report_type       varchar(20)     default 'SQL',
    datasource_key    varchar(50)     default 'master',
    sql_content       clob            not null,
    params_config     varchar(2000),
    columns_config    varchar(4000),
    output_format     varchar(20)     default 'EXCEL',
    status            varchar(1)      default '0',
    template_id       bigint          default null,
    create_by         varchar(64)     default '',
    create_time       timestamp       default current_timestamp,
    update_by         varchar(64)     default '',
    update_time       timestamp       null,
    remark            varchar(500)    default '',
    primary key (report_id)
);

drop table if exists sys_report_exec;
create sequence sys_report_exec_seq start with 100 increment by 1;
create table sys_report_exec (
    exec_id           bigint          not null,
    report_id         bigint          not null,
    report_name       varchar(100),
    exec_time         timestamp       default current_timestamp,
    exec_params       varchar(2000),
    output_format     varchar(20),
    file_path         varchar(500),
    file_size         bigint,
    status            varchar(1)      default '0',
    error_msg         varchar(2000),
    exec_duration     bigint,
    create_by         varchar(64),
    primary key (exec_id)
);

drop table if exists sys_report_template;
create sequence sys_report_template_seq start with 100 increment by 1;
create table sys_report_template (
    template_id         bigint          not null,
    template_name       varchar(200)    not null,
    template_key        varchar(100)    not null,
    description         varchar(500),
    datasource_key      varchar(100)    not null,
    report_mode         varchar(20)     default 'SQL',
    sql_content         clob,
    tables_config       clob,
    columns_config      clob,
    filters_config      clob,
    group_by_config     clob,
    order_by_config     clob,
    charts_config       clob,
    layout_config       clob,
    output_format       varchar(20)     default 'EXCEL',
    status              varchar(1)      default '0',
    version             int             default 1,
    parent_template_id  bigint,
    change_log          varchar(500),
    create_by           varchar(64),
    create_time         timestamp       default current_timestamp,
    update_by           varchar(64),
    update_time         timestamp       default current_timestamp,
    remark              varchar(500),
    primary key (template_id)
);

drop table if exists sys_report_email_config;
create sequence sys_report_email_config_seq start with 100 increment by 1;
create table sys_report_email_config (
    config_id           bigint          not null,
    report_id           bigint          not null,
    template_id         bigint,
    recipient_emails    clob,
    cc_emails           clob,
    email_subject       varchar(300),
    email_body          clob,
    attachment_format   varchar(20)     default 'EXCEL',
    send_on_success     varchar(1)      default '1',
    send_on_failure     varchar(1)      default '1',
    status              varchar(1)      default '0',
    create_time         timestamp       default current_timestamp,
    update_time         timestamp       default current_timestamp,
    primary key (config_id),
    foreign key (report_id) references sys_report(report_id) on delete cascade
);

-- 20. Email SMTP & Templates
drop table if exists sys_email_smtp_config;
create sequence sys_email_smtp_config_seq start with 100 increment by 1;
create table sys_email_smtp_config (
    config_id           bigint          not null,
    smtp_host           varchar(200)    not null,
    smtp_port           int             default 587,
    username            varchar(200)    not null,
    password            varchar(500)    not null,
    auth                varchar(1)      default '1',
    starttls_enable     varchar(1)      default '1',
    starttls_required   varchar(1)      default '1',
    ssl_enable          varchar(1)      default '0',
    timeout             int             default 5000,
    status              varchar(1)      default '0',
    create_time         timestamp       default current_timestamp,
    update_time         timestamp       default current_timestamp,
    primary key (config_id)
);

drop table if exists sys_job_email_template;
create sequence sys_job_email_template_seq start with 100 increment by 1;
create table sys_job_email_template (
    template_id        bigint           generated by default as identity,
    template_name      varchar(100)     not null,
    template_code      varchar(50)      not null unique,
    subject            varchar(255)     not null,
    content            clob             not null,
    datasource_key     varchar(50),
    query_sql          clob,
    include_data_table boolean          default false,
    data_tables        clob,
    status             varchar(1)       default '0',
    create_by          varchar(64)      default '',
    create_time        timestamp        default current_timestamp,
    primary key (template_id)
);

-- 21. AI Knowledge Base
drop table if exists ai_knowledge;
drop sequence if exists ai_knowledge_seq;
create sequence ai_knowledge_seq start with 100 increment by 1;
create table ai_knowledge (
  knowledge_id    bigint          not null,
  title           varchar(200)    not null,
  content         clob            not null,
  category        varchar(50)     default '',
  keywords        varchar(500)    default '',
  status          varchar(1)      default '1',
  create_by       varchar(64)     default '',
  create_time     timestamp       default current_timestamp,
  update_by       varchar(64)     default '',
  update_time     timestamp       null,
  remark          varchar(500)    default null,
  primary key (knowledge_id)
);

-- 22. Notification System
drop table if exists sys_notification;
create sequence sys_notification_seq start with 100 increment by 1;
create table sys_notification (
    notification_id     bigint          not null,
    user_id             bigint,
    title               varchar(200)    not null,
    content             clob,
    notification_type   varchar(50),
    channel             varchar(50),
    status              varchar(1)      default '0',
    link_url            varchar(500),
    create_time         timestamp       default current_timestamp,
    read_time           timestamp       null,
    expiry_time         timestamp,
    primary key (notification_id)
);

-- 23. Advanced Dashboard System
drop table if exists sys_dashboard;
create sequence sys_dashboard_seq start with 100 increment by 1;
create table sys_dashboard (
    dashboard_id    bigint          not null,
    dashboard_name  varchar(200)    not null,
    layout_config   clob,
    user_id         bigint,
    is_default      boolean         default false,
    create_time     timestamp       default current_timestamp,
    update_time     timestamp,
    primary key (dashboard_id)
);

drop table if exists sys_dashboard_widget;
create table sys_dashboard_widget (
    widget_id       bigint          primary key,
    dashboard_id    bigint,
    widget_type     varchar(50),
    title           varchar(200),
    query_sql       clob,
    chart_type      varchar(50),
    position_x      int,
    position_y      int,
    width           int,
    height          int,
    refresh_interval int,
    create_time     timestamp       default current_timestamp
);

-- 24. Quartz Core Tables (Standard H2)
drop table if exists QRTZ_FIRED_TRIGGERS;
drop table if exists QRTZ_PAUSED_TRIGGER_GRPS;
drop table if exists QRTZ_SCHEDULER_STATE;
drop table if exists QRTZ_LOCKS;
drop table if exists QRTZ_SIMPLE_TRIGGERS;
drop table if exists QRTZ_SIMPROP_TRIGGERS;
drop table if exists QRTZ_CRON_TRIGGERS;
drop table if exists QRTZ_BLOB_TRIGGERS;
drop table if exists QRTZ_TRIGGERS;
drop table if exists QRTZ_JOB_DETAILS;
drop table if exists QRTZ_CALENDARS;

create table QRTZ_JOB_DETAILS (
  sched_name        varchar(120)    not null,
  job_name          varchar(200)    not null,
  job_group         varchar(200)    not null,
  description       varchar(250)    null,
  job_class_name    varchar(250)    not null,
  is_durable        varchar(1)      not null,
  is_nonconcurrent  varchar(1)      not null,
  is_update_data    varchar(1)      not null,
  requests_recovery varchar(1)      not null,
  job_data          blob            null,
  primary key (sched_name, job_name, job_group)
);

create table QRTZ_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  job_name       varchar(200)    not null,
  job_group      varchar(200)    not null,
  description    varchar(250)    null,
  next_fire_time bigint          null,
  prev_fire_time bigint          null,
  priority       integer         null,
  trigger_state  varchar(16)     not null,
  trigger_type   varchar(8)      not null,
  start_time     bigint          not null,
  end_time       bigint          null,
  calendar_name  varchar(200)    null,
  misfire_instr  smallint        null,
  job_data       blob            null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, job_name, job_group) references QRTZ_JOB_DETAILS(sched_name, job_name, job_group)
);

create table QRTZ_SIMPLE_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  repeat_count   bigint          not null,
  repeat_interval bigint         not null,
  times_triggered bigint         not null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

create table QRTZ_CRON_TRIGGERS (
  sched_name     varchar(120)    not null,
  trigger_name   varchar(200)    not null,
  trigger_group  varchar(200)    not null,
  cron_expression varchar(200)   not null,
  time_zone_id   varchar(80)     null,
  primary key (sched_name, trigger_name, trigger_group),
  foreign key (sched_name, trigger_name, trigger_group) references QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group)
);

create table QRTZ_CALENDARS (
  sched_name     varchar(120)    not null,
  calendar_name  varchar(200)    not null,
  calendar       blob            not null,
  primary key (sched_name, calendar_name)
);

create table QRTZ_PAUSED_TRIGGER_GRPS (
  sched_name     varchar(120)    not null,
  trigger_group  varchar(200)    not null,
  primary key (sched_name, trigger_group)
);

create table QRTZ_FIRED_TRIGGERS (
  sched_name      varchar(120)    not null,
  entry_id        varchar(95)     not null,
  trigger_name    varchar(200)    not null,
  trigger_group   varchar(200)    not null,
  instance_name   varchar(200)    not null,
  fired_time      bigint          not null,
  sched_time      bigint          not null,
  priority        integer         not null,
  state           varchar(16)     not null,
  job_name        varchar(200)    null,
  job_group       varchar(200)    null,
  is_nonconcurrent varchar(1)     null,
  requests_recovery varchar(1)    null,
  primary key (sched_name, entry_id)
);

create table QRTZ_SCHEDULER_STATE (
  sched_name      varchar(120)    not null,
  instance_name   varchar(200)    not null,
  last_checkin_time bigint        not null,
  checkin_interval bigint         not null,
  primary key (sched_name, instance_name)
);

create table QRTZ_LOCKS (
  sched_name      varchar(120)    not null,
  lock_name       varchar(40)     not null,
  primary key (sched_name, lock_name)
);